version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 5673:5673
      - 15672:15672
      - 15674:15674
      - 15671:15671
    volumes:
      - rabbitvol:/var/lib/rabbitmq
    networks:
      - broker

  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090

  prometheus:
    image: prom/prometheus:v2.40.4
    ports:
      - 9090:9090
    networks:
      - monitoring
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.3.0
    ports:
      - 3000:3000 
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana_data:/var/lib/grafana

networks:
  broker:
    driver: bridge
  monitoring:

volumes:
  rabbitvol:
    driver: local
  grafana_data: { }