version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 5673:5673
      - 15672:15672
      - 15674:15674
      - 15671:15671
    volumes:
      - rabbitvol:/var/lib/rabbitmq
    networks:
      - broker

networks:
  broker:
    driver: bridge

volumes:
  rabbitvol:
    driver: local